routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');
Route::get('password/email', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

Route::get('home', function() {
    return Redirect::to('/');
});

Route::get('dealer-order-form', function() {
    return view('dealer-order-form');
});
Route::get('customer-order-form', function() {
    return view('customer-order-form');
});

Route::get('esign/errors', ['as' => 'order-esign-errors', 'uses' => 'EsignController@errors']);
Route::get('esign/thanks', ['as' => 'order-esign-thanks', 'uses' => 'EsignController@thanks']);
Route::post('esign-callback', ['as' => 'esign-callback', 'uses' => 'EsignController@callback']);

// lock to dealer role
Route::get('orders/{order_uuid}/initial-esign', ['as' => 'order-esign', 'uses' => 'OrdersController@initialEsignOrderDocument']);
Route::get('orders/{order_uuid}/esign-via-email', ['as' => 'order-esign-email', 'uses' => 'OrdersController@esignOrderDocumentViaEmail']);

// rto company
Route::get('orders/{order_uuid}/esign/{signature_id}', ['as' => 'esign-order-by-signature-id', 'uses' => 'OrdersController@esignOrderDocumentBySignatureId']);

Route::get('dealer-map', function() {
    return view('dealer-map');
});
Route::get('inventory_building/{inventory_building}', 'BuildingsController@pdfInitialInventoryForm');
Route::get('documents/price-list', 'DocumentsController@priceList');
Route::get('documents/order-form', 'DocumentsController@orderForm');
Route::get('documents/rto-docs', 'DocumentsController@rtoDocs');
Route::get('documents/promo99', 'DocumentsController@promo99');
Route::get('documents/building-configuration', 'DocumentsController@buildingConfiguration');
Route::get('documents/delivery-form', 'DocumentsController@deliveryForm');
Route::get('documents/neighbor-release', 'DocumentsController@neightborRelease');

Route::get('buildings/{building}/inventory-form', 'BuildingsController@pdfInventoryForm');

Route::get('/', 'HomeController@index');

Route::group(['middleware' => 'uscguard' ], function() {
    
    Route::get('buildings/{building}/work-form', 'BuildingsController@pdfWorkForm')->name('building/work-form');
    Route::get('buildings/{building}/work-building-form', 'BuildingsController@pdfWorkBuildingForm')->name('building/work-building-form');
    Route::get('buildings/import', 'BuildingsController@import');
    Route::resource('buildings', 'BuildingsController');
    Route::resource('building-models', 'BuildingModelsController');
    Route::resource('building_statuses', 'BuildingStatusesController');
    Route::resource('building-packages', 'BuildingPackagesController');
    Route::resource('building-package-categories', 'BuildingPackagesCategoriesController');

    Route::resource('materials', 'MaterialsController');
    Route::resource('material_categories', 'MaterialCategoriesController');
    Route::resource('plants', 'PlantsController');
    Route::resource('styles', 'StylesController');
    Route::resource('options', 'OptionsController');
    Route::resource('option_packages', 'OptionPackagesController');
    Route::resource('locations', 'LocationsController');
    Route::resource('settings', 'SettingsController');
    Route::resource('colors', 'ColorsController');
    Route::resource('dealers', 'DealersController');
    Route::resource('deliveries', 'DeliveriesController');
    Route::resource('orders', 'OrdersController');
    Route::resource('sales', 'SalesController');

    Route::resource('employees', 'EmployeesController');
    // Route::resource('leads', 'LeadsController');
    Route::get('option-categories', 'OptionCategoriesController@index');

    Route::get('reports', 'ReportsController@index');
    Route::post('reports/ajax-report/{report_type}', 'ReportsController@ajaxReport');

    Route::get('bills/report', 'BillsController@report');
    Route::resource('bills', 'BillsController', ['only' => ['create', 'show', 'store', 'index']]);

    Route::get('expenses/report', 'ExpensesController@report');
    Route::resource('expenses', 'ExpensesController', ['only' => ['']]);
    Route::group(['prefix' => 'reports'],function(){
        Route::get('Chart', 'ReportsController@chartsData');
        Route::get('Chart/production', 'ReportsController@productionChartsData');
    });
    Route::get('print/{identifier}','PrintController@showprint');
});

Route::group(['middleware' => ['auth','qraccess'] ], function() {
        Route::resource('qrcode', 'QrcodeController');
});

app/Models/Bill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Bill extends Model
{
    use SoftDeletes;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'bills';

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id', 'date', 'amount'];

    protected $appends = ['number'];

    /**
     * A bill has many expenses
     * @return \App\Models\BuildingLocation
     */
    public function expenses()
    {
        return $this->hasMany('App\Models\Expense', 'bill_id', 'id');
    }

    /**
     * A bill belongs to user (contractor)
     * @return \App\Models\User
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    /**
     * Get the bill number attribute (temp format).
     *
     * @param  string  $value
     * @return string
     */
    public function getNumberAttribute($value)
    {
        return str_replace('-', '', $this->date) . '-' . $this->user_id;
    }

    /**
     * Get all of the building history that are assigned this bill.
     */
    public function building_history()
    {
        return $this->morphedByMany('App\Models\BuildingHistory', 'expense')->withPivot(['expense_type', 'cost']);
    }

    /**
     * Get all of the building locations that are assigned this bill.
     */
    public function building_locations()
    {
        return $this->morphedByMany('App\Models\BuildingLocation', 'expense')->withPivot(['expense_type', 'cost']);
    }

    /**
     * Get all of the owning billable models.
     */
    public function getBillableAttribute($value)
    {
        // There two calls return collections
        // as defined in relations.
        $stack = collect ([
            $this->getRelation('building_history'),
            $this->getRelation('building_locations')
        ]);

        // Merge collections and return single collection.
        return $stack->collapse();
    }
}

app/Http/Controllers/BillsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use Auth;
use App\Models\User;
use App\Models\Bill;
use App\Models\Expense;
use App\Models\Building;
use App\Models\BuildingHistory;
use App\Models\BuildingLocation;

use App\Jobs\CreateBills;
use App\Http\Requests\AddBillRequest;
use Mockery\CountValidator\Exception;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Eloquent\Collection;

use App\Services\Reports\BillReportService;

class BillsController extends Controller
{
    private $route_name = 'bills';

    private $params = [];

    public function __construct()
    {
        $this->params = [
            'breadcrumbs' => [
                ['url' => '/', 'page' => 'Bills']
            ],
            'title' => 'Bills',
            'subtitle' => 'Bills',
            'search' => 'yes',
            'filter' => '',
            'items_per_page' => 500,
            'route_name' => $this->route_name,
            'route' => '/' . $this->route_name,
            'data' => null,
        ];
    }

    public function index()
    {
        array_push($this->params['breadcrumbs'], ['url' => '', 'page' => 'Create']);

        $users[0] = ['value' => null, 'display' => 'None', 'options' => [ 'disabled' => true ]];
        $users['all'] = ['value' => 'all', 'display' => '- All -'];
        User::get()->each(function($user, $key) use (&$users) {
            $users[$user->id] = [
                'value' => $user->id,
                'display' => $user->first_name.' '.$user->last_name
            ];
        });

        $this->params['data']['users'] = $users;
        $this->params['subtitle'] = 'Create Bill';
        return view($this->route_name . '.index')->withParams($this->params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        array_push($this->params['breadcrumbs'], ['url' => '', 'page' => 'Create']);

        $users[0] = ['value' => null, 'display' => 'None', 'options' => [ 'disabled' => true ]];
        $users['all'] = ['value' => 'all', 'display' => '- All -'];
        User::get()->each(function($user, $key) use (&$users) {
            $users[$user->id] = [
                'value' => $user->id,
                'display' => $user->first_name.' '.$user->last_name
            ];
        });

        $this->params['data']['users'] = $users;
        $this->params['subtitle'] = 'Create Bill';
        return view($this->route_name . '._form')->withParams($this->params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AddBillRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddBillRequest $request)
    {
        try
        {
            $userID = $request->get('user_id');
            $billsInfo = $this->dispatch(new CreateBills($userID));

            if ( $billsInfo['summary']['count'] > 0 )
                $message[] = 'Bills successfully generated.';
            else
                $message[] = 'There is no unbilled changes.';

            return response()->json(array(
                'success' => true,
                'message' => $message,
                'payload' => $billsInfo
            ));
        } catch (Exception $e)
        {
            return response()->json(array(
                'success' => false,
                'message' => [ 'Sorry, there was an error saving the record.' ]
            ));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        array_push($this->params['breadcrumbs'], ['url' => '', 'page' => 'View Bill']);

        /*Relation::morphMap([
            'status' => BuildingHistory::class,
            'location' => BuildingLocation::class,
        ]);*/

        $this->params['data']['item'] = $bill = Bill::with([
            'user',
            'building_history.building',
            'building_history.contractor',
            'building_history.building_status',
            'building_locations.driver',
            'building_locations.building'
        ])->findOrFail($id);

        $this->params['subtitle'] = 'Bill #' . $bill->number;

        return view($this->route_name . '.details')->withParams($this->params);
    }

    /**
     * Display a listing of the resource.
     *
     * @param ReportService|BillReportService $billReport
     * @return \Illuminate\Http\Response
     */
    public function report(BillReportService $billReport)
    {
        array_push($this->params['breadcrumbs'], ['url' => '', 'page' => 'Report']);

        $rules['bill_report'] = $billReport->getRules();

        $this->params['rules'] = $rules;
        $this->params['subtitle'] = 'Bill Report';
        return view($this->route_name . '.report')->withParams($this->params);
    }
}

resources/views/bills/_form.blade.php
@extends('partials._base')

@section('panel-body')
    <h5>
        This will generate a bill number for all unbilled status and location changes
    </h5>

    @include('partials._forms')
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-xs-12 col-md-3">
                {!! Form::label('user_id', 'User', ['class' => 'control-label']) !!}
                {!! Form::custom_select('user_id', $params['data']['users'], null, ['id' => 'user_id', 'name' => 'user_id', 'data-plugin-selectTwo', 'class' => 'form-control populate']) !!}
            </div>
        </div>
    </div>

    <div id="form-msg-area" class="mt-sm">

    </div>
@endsection


@section('panel-footer')
    <div class="panel-footer clearfix">
        <div class="pull-left">
            {!! Form::button('Generate', ['class' => 'btn btn-primary', 'id' => 'create_bill_button', 'data-loading-text' => 'Generating..']) !!}
        </div>
        {!! Form::close() !!}
    </div>
@endsection

@section('footer-scripts')
    @parent

    <script type="text/template" id="tpl-create-bill-res">

        <% if( typeof(data['bills']) !== 'undefined' && !_.isEmpty(data['bills']) ) { %>
        <dl class="dl-horizontal">
            <dt>Count bills</dt>
            <dd><%= data.summary.count %></dd>

            <dt>Total amount</dt>
            <dd>$<%= data.summary.total %></dd>
        </dl>

        <div class="dataTables_wrapper no-footer">
            <div class="table-responsive col-xs-12 col-md-6">
                <table class="table table-striped table-condensed mb-none no-footer">

                    <thead>
                    <tr>
                        <th class="text-left">User</th>
                        <th class="text-left">Bill #</th>
                        <th class="text-left">Date</th>
                        <th class="text-left">Amount</th>
                    </tr>
                    </thead>
                    <tbody>

                    <% _.forEach(data['bills'], function(bill) { %>
                        <tr>
                            <td class="text-left"><%= bill['full_name'] %></td>
                            <td class="text-left"><a href="{{ route('bills.show', ['bills' => '']) }}/<%= bill['id'] %>"><%= bill['number'] %></a></td>
                            <td class="text-left"><%= bill['date'] %></td>
                            <td class="text-left">$<%= bill['amount'] %></td>
                        </tr>
                    <% }); %>

                    </tbody>
                </table>
            </div>
        </div>
        <% } %>

    </script>

    <script type="text/javascript" charset="utf-8">
        (function( $, _ ) {
            'use strict';

            var BillCreate = {
                dom: {
                    $panel: {},
                    $form: {},
                    $form_fields: {},
                    $form_create_button: {},
                    $form_msg_area: {},
                },
                templates: {},

                initialize: function() {
                    this.initializeDom();
                    this.initializeTemplates();
                    this.initializeFormCreateButton();
                },

                initializeDom: function() {
                    var $form = $('form');
                    this.dom.$form = $form;
                    this.dom.$panel = $form.parent().parent().parent();
                    this.dom.$form_create_button = $('#create_bill_button');
                    this.dom.$form_msg_area = $('#form-msg-area');

                    this.dom.$form_fields['_token'] = $form.find('input[name="_token"]');
                    this.dom.$form_fields['user_id'] = $form.find('#user_id');
                },

                initializeTemplates: function() {
                    this.templates.tpl_create_bills_res = _.template($('#tpl-create-bill-res').html());
                },

                initializeFormCreateButton: function() {
                    var self = this;

                    this.dom.$form_create_button.on('click', function() {
                        var $this = $(this);

                        self.createBills(
                                self.dom.$form.attr('action'),
                                {},
                                {},
                                function() {
                                    //$this.button('loading');
                                    self.dom.$form_msg_area.empty();
                                    self.dom.$panel.loadingOverlay({
                                        //startShowing: true,
                                        css: {
                                            'background-color': 'rgba(0, 0, 0, 0.075)'
                                        }
                                    });

                                    self.dom.$panel.trigger( "beforeSend" );
                                },
                                function(data) {
                                    var is_success = self.parseCreateBills('success', data, self.dom.$form_msg_area);
                                    if(is_success) {
                                        self.renderResults(data);
                                    }
                                    //$this.button('reset');
                                },
                                function(data) {
                                    self.parseCreateBills('error', data, self.dom.$form_msg_area);
                                    //$this.button('reset');
                                }
                        );
                    });
                },

                createBills: function(request_url, form_fields, form_data, precall, callback_success, callback_error) {
                    var params = this.collectFormData(this.dom.$form_fields, form_fields);

                    $.extend(true, params, form_data);
                    precall();
                    $.ajax({
                        url: request_url,
                        headers: {},
                        dataType: "json",
                        type: 'POST',
                        data: params,
                        success: function(data) {
                            callback_success(data);

                        },
                        error: function(data) {
                            callback_error(data);
                        }
                    });
                },

                parseCreateBills: function(type, data, $_result_msg_area) {
                    var self = this;
                    var is_success = false;
                    $_result_msg_area.empty();

                    if ( type == 'error') {
                        if( data.status === 422 && typeof data['responseJSON'] === 'object') {
                            $.each(data['responseJSON'], function(index, value) {
                                $_result_msg_area.append('<div class="alert alert-danger"><i class="fa fa-remove"></i> ' +
                                        value +
                                        '</div>');
                            });
                        } else {
                            $_result_msg_area.append('<div class="alert alert-danger"><i class="fa fa-remove"></i> ' +
                                    'An internal error was encountered while processing this request' +
                                    '</div>');
                        }
                    }

                    if ( type == 'success') {
                        if ( data == null )
                            return is_success;

                        var json = data;
                        if( typeof json === 'object') {
                            if ( typeof json['success'] !== 'undefined' && json['success'] )
                                is_success = true;

                            if ( typeof json['message'] !== 'undefined' ) {
                                $.each(json['message'], function(index, value) {
                                    $_result_msg_area.append('<div class="alert alert-success"><i class="fa fa-check"></i> ' +
                                            value +
                                            '</div>');
                                });
                            }
                        }
                    }

                    self.dom.$panel.trigger( "complete" );
                    return is_success;
                },

                collectFormData: function($_form, params) {
                    var data = {};
                    $.each(this.dom.$form_fields, function(index, value) {
                        data[index] = value.val();
                    });

                    return data;
                },

                renderResults: function(data) {
                    var resultTable = this.templates.tpl_create_bills_res({
                        data: data['payload']
                    });

                    var $resultTable = $(resultTable);
                    this.dom.$form_msg_area.append($resultTable);
                }
            };

            BillCreate.initialize();

        }).apply(this, [ jQuery, _ ]);
    </script>
@endsection

resources/views/bills/_report_tpl.blade.php
@section('specifics-scripts')
    @parent
    <script type="text/template" id="report-stat-table-body">
        <% for (var index_row in o) { %>

        <tr>
            <% if (typeof o[index_row]['bill_number'] !== 'undefined') { %>
            <td class=""><a href="{{ route('bills.show', ['bills' => '']) }}/<%=o[index_row]['id']%>"><%=o[index_row]['bill_number']%></a></td>
            <% } %>

            <% if (typeof o[index_row]['date'] !== 'undefined') { %>
            <td class=""><%=o[index_row]['date_formatted']%></td>
            <% } %>

            <% if (typeof o[index_row]['user_id'] !== 'undefined') { %>
            <td class=""><%=o[index_row]['user']['full_name']%></td>
            <% } %>

            <% if (typeof o[index_row]['amount_formatted'] !== 'undefined') { %>
            <td class="">$<%=o[index_row]['amount_formatted']%></td>
            <% } %>

        </tr>

        <% } %>
    </script>

@endsection

resources/views/bills/details.blade.php
@extends('partials._base')

@section('panel-body')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
                <section class="panel">
                    <header class="panel-heading">
                        <h4 class="panel-title">Details</h4>
                    </header>
                    <div class="panel-body">
                        <dl class="dl-horizontal">
                            <dt>Bill #</dt>
                            <dd>{{ $params['data']['item']->number }}</dd>
                            <dt>Contractor</dt>
                            <dd>{{ $params['data']['item']->user->full_name }}</dd>
                            <dt>Date</dt>
                            <dd>{{ $params['data']['item']->date }}</dd>
                            <dt>Mail payment to</dt>
                            <dd>{{ $params['data']['item']->user->email }}</dd>
                        </dl>
                    </div>
                </section>

                @if ($params['data']['item']->billable)
                    <div class="dataTables_wrapper no-footer">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-condensed mb-none no-footer" >
                                <thead>
                                <tr>
                                    <th class="text-center">Building ID</th>
                                    <th class="text-left">Detail</th>
                                    <th class="text-left">Amount</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($params['data']['item']->billable->sortBy('created_at') as $billable_item)

                                    <tr>
                                        <td class="text-center">
                                            <a href="{{ route('buildings.show', ['building' => $billable_item->building->id]) }}">{{ $billable_item->building->serial_number }}</a>
                                        </td>
                                        <td class="text-left">
                                            @if( $billable_item->pivot->expense_type == 'location' )
                                                Delivered to <u>{{ $billable_item->location->name }}</u>
                                            @elseif( $billable_item->pivot->expense_type == 'status' )
                                                {{ $billable_item->building_status->name }}
                                            @endif
                                        </td>
                                        <td class="text-left">${{ number_format($billable_item->pivot->cost, 2) }} </td>
                                    </tr>
                                @endforeach

                                <tr>
                                    <td colspan="2"></td>
                                    <td class="text-left"><strong>Total</strong></td>
                                </tr>

                                <tr>
                                    <td colspan="2"></td>
                                    <td class="text-left">${{ number_format($params['data']['item']->amount, 2) }}</td>
                                </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                @else
                    <p>No options found for this building.</p>
                @endif


            </div>
        </div>

    </div>
@endsection